import { User } from '@/types/auth'
import { Order } from '@/types/order'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'demo@example.com',
    password: 'password123', // In production, this would be hashed
    firstName: 'Demo',
    lastName: 'User',
    phone: '+1 (555) 123-4567',
    address: '123 Fashion Ave',
    city: 'New York',
    country: 'United States',
    zipCode: '10001',
    createdAt: new Date('2024-01-15'),
    role: 'customer',
  },
  {
    id: 'admin-1',
    email: 'admin@example.com',
    password: 'admin123',
    firstName: 'Admin',
    lastName: 'User',
    phone: '+1 (555) 987-6543',
    address: '456 Admin Plaza',
    city: 'New York',
    country: 'United States',
    zipCode: '10002',
    createdAt: new Date('2024-01-01'),
    role: 'admin',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    userId: 'user-1',
    items: [
      {
        productId: 'prod-1',
        productName: 'Classic White Tee',
        quantity: 1,
        size: 'M',
        color: 'White',
        price: 45,
      },
      {
        productId: 'prod-3',
        productName: 'Premium Denim',
        quantity: 1,
        size: 'M',
        color: 'Dark Blue',
        price: 120,
      },
    ],
    shippingInfo: {
      firstName: 'Demo',
      lastName: 'User',
      email: 'demo@example.com',
      phone: '+1 (555) 123-4567',
      address: '123 Fashion Ave',
      city: 'New York',
      country: 'United States',
      zipCode: '10001',
    },
    billingInfo: {
      firstName: 'Demo',
      lastName: 'User',
      email: 'demo@example.com',
      phone: '+1 (555) 123-4567',
      address: '123 Fashion Ave',
      city: 'New York',
      country: 'United States',
      zipCode: '10001',
    },
    subtotal: 165,
    shippingCost: 10,
    tax: 14,
    total: 189,
    status: 'delivered',
    paymentMethod: 'credit_card',
    paymentStatus: 'completed',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'order-2',
    userId: 'user-1',
    items: [
      {
        productId: 'prod-2',
        productName: 'Elegant Black Dress',
        quantity: 1,
        size: 'S',
        color: 'Black',
        price: 280,
      },
    ],
    shippingInfo: {
      firstName: 'Demo',
      lastName: 'User',
      email: 'demo@example.com',
      phone: '+1 (555) 123-4567',
      address: '123 Fashion Ave',
      city: 'New York',
      country: 'United States',
      zipCode: '10001',
    },
    billingInfo: {
      firstName: 'Demo',
      lastName: 'User',
      email: 'demo@example.com',
      phone: '+1 (555) 123-4567',
      address: '123 Fashion Ave',
      city: 'New York',
      country: 'United States',
      zipCode: '10001',
    },
    subtotal: 280,
    shippingCost: 10,
    tax: 23,
    total: 313,
    status: 'shipped',
    paymentMethod: 'credit_card',
    paymentStatus: 'completed',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-28'),
  },
]
